### ISSUE TITLE
Event details page hangs after scroll.

### ISSUE THREAD

**Issue by andela-ioraelosi** [andela/roots#116]
When I select an event and scroll to the bottom, I can no longer scroll to the event page. To replicate this:

- [ ] Visit the site.
- [ ] Click on a featured event.
- [ ] Scroll to the bottom of the page.
- [ ] Attempt to scroll up.

**Comment by andela-toladele** [comment]
It appeared to be hanging because the mouse was on the google map, and it was loading an address that wasn't available
