### ISSUE TITLE
Organizer profile image does not load when creating organizer profile

### ISSUE THREAD

**Issue by andela-toladele** [andela/roots#120]
How to replicate

-Visit the sit
-Log in or sign up with a new user account
-From the drop down menu on the top right bar click 'My profile link'
-Click the My organizer profile tab
- If organizer profile already exists, click the edit button and delete the organizer profile
-Fill in the organizer details and upload profile image
-Click save changes
-View switches to readonly mode, but it doesn't load the organizer profile image

**Comment by andela-eashikodi** [comment]
This is fixed yeah!
