### ISSUE TITLE
User details are not reflected on the top navbar after editing user profile details

### ISSUE THREAD

**Issue by andela-toladele** [andela/roots#121]
How to replicate

-Visit the sit
-Log in or sign up with a new user account
-From the drop down menu on the top right bar click 'My profile link'
-Click the My edit profile tab
-Edit the user first name field or upload a new profile image
-Click save changes
-View switches to readonly mode, but changes are not reflected on the top navbar

**Comment by andela-uopaluwa** [comment]
fixed.
